Login/register forms
FIT-2024-RecALL/recall-front pull request #14
Opened 2024-10-18 19:52 UTC by KozlovKV

2024-10-21 07:36 UTC, mordv requested changes
Четко, правки минимальны.

2024-10-21 07:36 UTC, mordv commented on src/components/LoginForm.tsx
> +          {errors.email?.message.toString()}
TS знает, что email точно не undefined - выше ты это проверил. ?. здесь излишен. Снизу так же.

2024-10-21 07:36 UTC, mordv commented on src/components/library/SliderCheckbox.tsx
> +    <>
<> это Fragment, здесь он не нужен

2024-10-21 07:36 UTC, mordv commented on src/components/library/SliderCheckbox.tsx
> +  let checkedForStyle = checked;
Не понял, что хочешь сделать, но мне не нравится. let вообще в кодобазе должен быть сведен к минимуму. Здесь хватит тернарника.

2024-10-21 07:36 UTC, mordv commented on yarn.lock
>      commander "12.1.0"
Определитесь, что вы используете npm или yarn. В репозитории должен быть только один lock файл.

2024-10-21 07:36 UTC, mordv commented on src/components/library/SliderCheckbox.tsx
> +  onClick: (checked?: boolean) => void;
Вот это неправда, checked он не передает никогда

2024-10-21 07:36 UTC, mordv commented on src/components/RegisterForm.tsx
> +      <input
По-хорошему, я бы сделал компонент FormItem, куда бы передавал label и error. А сам инпут - как child

```tsx
<FormItem
            className={'min-h-[70px]'}
            label={'Имя пользователя'}
            required
            error={errors.username?.message}
          >
            <Input {...register('username')} />
          </FormItem>
```

2024-10-23 11:09 UTC, KozlovKV commented on src/components/library/SliderCheckbox.tsx
> +  let checkedForStyle = checked;
Мне хотелось сделать независимые друг от друга стиль слайдера и перемещение его влево-вправо и при этом добавить различные варианты стиля, в том числе не зависящие от положения слайдера. Сделал объект с функциями-трансформерами

2024-10-23 11:12 UTC, KozlovKV commented on src/components/library/SliderCheckbox.tsx
> +  onClick: (checked?: boolean) => void;
Не совсем понял. Получается, `checked` сделать стэйтом этого компонента? Просто местами было удобно, что он берётся от логической переменной где-то выше

2024-10-23 11:14 UTC, KozlovKV commented on src/components/library/SliderCheckbox.tsx
> +  onClick: (checked?: boolean) => void;
А! Речь о том, что принимает функция `onClick`. Тут согласен

2024-10-23 11:39 UTC, KozlovKV commented on src/components/RegisterForm.tsx
> +      <input
Вроде бы сделал. Кода стало действительно чуть поменьше, но не уверен, что это будет всегда удобно использовать. Хотя... И каких-то особо специфичных форм у нас вроде не планируется

2024-10-23 11:39 UTC, KozlovKV commented on yarn.lock
>      commander "12.1.0"
А я вообще не знаю, откуда он появляется...

2024-10-24 07:05 UTC, mordv commented on yarn.lock
>      commander "12.1.0"
lock файл генерируется при `npm install` или `yarn install`

2024-10-24 15:41 UTC, merged