Card
FIT-2024-RecALL/recall-front pull request #18
Opened 2024-10-26 21:46 UTC by KozlovKV

Добавил карточку с возможностью вспылтия и переворачивания. Перед переходом к теме редактирования надо добавить прокидывание пропсов с её содержимым

2024-10-27 20:38 UTC, KozlovKV commented on src/pages/CollectionEditPage.tsx
> +  const collection = useAppStore((state) => state.getCollection)(Number(id));
@mordv , сразу несколько вопросов насчёт этого места:
- Хорошо ли так пользоваться селекторами из стора?
- Стоит ли вообще использовать сторы для того, чтобы хранить какое-то время много данных или лучше в таком слует посылать GET-запрос по id-коллекции на бэк каждый раз?

2024-10-28 06:33 UTC, mordv requested changes

2024-10-28 06:33 UTC, mordv commented on src/state/slices/CollectionsState.ts
> +      'Card content. Card content. Card content. Card content. Card content. Card content. Card content. Card content. Card content. Card content. Card content. Card content. Card content. Card conte
'Card content. '.repeat(1000)  :)

2024-10-28 06:33 UTC, mordv commented on src/state/slices/CollectionsState.ts
> +  collections: [CollectionType];
Это tuple из одного элемента. Скорее всего ты имел в виду T[] а не [T]

2024-10-28 06:33 UTC, mordv commented on src/components/card/CardSide.tsx
> +  const getSideAnimationClass = (side: CardSides) => {
Во - первых, утилиты лучше выносить за компонент,
Во-вторых, оставь пожилые языковые конструкции в покое

```
const animations = { // это за компонентом
  back: 'flip-back',
  front: 'flip-front',
} satisfies Record<CardSides, string> // ts тебя проверит

animations['front'] // и тут ts тебя проверит
```

2024-10-28 06:33 UTC, mordv commented on src/components/card/CardSide.tsx
> +  const getSideAnimationClass = (side: CardSides) => {
При этом, TS здесь реально проверит, что ты все CardSides прогнал (представь, что это не Side, а Variant и ты добавил новый)
Switch-case пропустит неполное покрытие (только линтер может ругнуться)

2024-10-28 06:33 UTC, mordv commented on src/components/card/FlippingCard.tsx
> +          <Button variant="bordered" onClick={() => setFlipped(!flipped)}>
setFlipped(f => !f)

сеттеры могут принимать лямбду. Первый ее параметр - это предыдущее значение. Иногда тебе это сэкономит переменную в deps array.

2024-10-28 06:33 UTC, mordv commented on src/components/card/MiniCard.tsx
> +        if (onClick) onClick();
onClick?.()

2024-10-28 06:33 UTC, mordv commented on src/pages/CollectionEditPage.tsx
> +  const collection = useAppStore((state) => state.getCollection)(Number(id));
1. Абсолютно нехорошо, стор не должен содержать геттеров. Функции в сторе - это actions. Все, что ты хочешь взять из стора, выбираешь селекторами, которые можешь писать in-place, а можешь хранить где-нибудь глобально
![image](https://github.com/user-attachments/assets/32dd37f7-b5d0-4d67-a612-5b40c2ce9b39)

Конкретно в таких случаях, я делаю factorySelector 
```tsx
projectSelectorFactory: (id: string) => (s: AppState) => s.projects[id]

...
const project = useStore(Selectors.projectSelectorFactory(id))
```

2. По ситуации. Иногда react-query берет это на себя

2024-10-28 12:57 UTC, KozlovKV commented on src/pages/CollectionEditPage.tsx
> +  const collection = useAppStore((state) => state.getCollection)(Number(id));
Я чувствовал! Чувствовал, что это нечто очень кривое. Поправил (надеюсь). А про rq почитаю, спасибо

2024-10-29 04:52 UTC, mordv approved these changes

2024-10-29 06:05 UTC, merged