Text editor
FIT-2024-RecALL/recall-front pull request #20
Opened 2024-10-31 15:40 UTC by KozlovKV

Добавил markdown-разметку с мультимедия.

Осталось разобраться с латехом, но это, возможно, оставлю на потом (там трабблы с отсутствием типов для плагинов. Возможно, придётся пилить свой, используя `katex`)

2024-11-05 16:10 UTC, mordv requested changes

2024-11-05 16:10 UTC, mordv commented on src/components/editor/EditorComponent.tsx
> +            __html: extendedMdRenderer.render(editorState),
Замемойзить надо. Только не вызывай .render на каждое изменение. Если active === false, useMemo пусть возвращает undefined

2024-11-05 16:10 UTC, mordv commented on src/pages/CollectionEditPage.tsx
> +    <Card cardData={JSON.parse(JSON.stringify(card))} mode="edit" key={card.id} />
Зачем?

2024-11-05 16:10 UTC, mordv commented on src/pages/CollectionEditPage.tsx
> +    <Card cardData={JSON.parse(JSON.stringify(card))} mode="edit" key={card.id} />
Боишься его в useState(initialState); сунуть?

2024-11-07 13:13 UTC, KozlovKV commented on package.json
> +    "@types/markdown-it": "^14.1.2",
Нет... Он как-то мимо проскочил. А разве типы в types не сами авторы зачастую делают?

Ну и `markdown-it` вроде до сих пор поддерживается

2024-11-07 13:14 UTC, KozlovKV commented on package.json
> +    "@types/markdown-it": "^14.1.2",
Но сейчас посмотрел про remark. Вроде как она будет приятнее гораздо, однако сейчас есть задачи приоритетнее (доработка логики работы с карточками, страница коллекции, тренировка), так что я оставлю таску на переход на remark на потом

2024-11-07 13:29 UTC, KozlovKV commented on src/components/editor/EditorComponent.tsx
> +            __html: extendedMdRenderer.render(editorState),
Использовать как триггер useMemo флаг расфокусировки будет норм?

А почему возвращать undefined? Если active === false, то нас как раз и интересует отрендеренное содержимое

2024-11-07 13:30 UTC, KozlovKV commented on src/pages/CollectionEditPage.tsx
> +    <Card cardData={JSON.parse(JSON.stringify(card))} mode="edit" key={card.id} />
Кажется, мне мешали readonly, но если тебе мешают readonly, то что-то наверняка не так. Больше они не мешают, так что от этой странной штуки я тоже избавился

2024-11-07 18:22 UTC, mordv commented on src/pages/CollectionEditPage.tsx
> +    <Card cardData={JSON.parse(JSON.stringify(card))} mode="edit" key={card.id} />
Если в каких-то ситуациях хочешь заткнуть TS (они редки, но возникают) - используй каст `as unknown as type` или вообще `as any` runtime overhead это не привнесет (в отличии от JSON.parse)

2024-11-07 18:37 UTC, mordv commented on src/components/editor/EditorComponent.tsx
> +            __html: extendedMdRenderer.render(editorState),
Я бы предложил зависеть от [active, editorState] и возвращать undefined при active === true (изначально написал неправильно, но ты меня понял). Теперь уже не думаю, что Object.is() двух жирных строк на каждое нажатие клавиши это сильно лучше, чем без мемойза вообще :)
С фокусом надо вникать, нет ли там блика старого значения при ререндеренге. Оставь, в общем без мемойза и принимай :)

2024-11-07 18:48 UTC, KozlovKV commented on package.json
> +    "@types/markdown-it": "^14.1.2",
Ну... Может пакет не утяжелять чтобы. Но в общем-то согласен

2024-11-07 19:08 UTC, mordv commented on package.json
> +    "@types/markdown-it": "^14.1.2",
Типы так и так не идут в бандл

2024-11-07 19:52 UTC, merged