Interactive cards
FIT-2024-RecALL/recall-front pull request #26
Opened 2024-11-07 19:59 UTC by KozlovKV

По планам тут:
- [ ] Добавить слайс для активной карточки и передавать благодаря ему данные из md-редакторов к компоненту с кнопкой сохранения
- [ ] Добавить псевдо-карточку, которая позволит создавать новые карточки
- [ ] Добавить поле для создания связей карточки с коллекциями

Очень скоро ожидается авторизация, после неё это всё сможет стать уже не псевдо-интерактивным, а прямо взаправду

2024-11-07 20:00 UTC, KozlovKV commented on src/components/card/FlippingCard.tsx
>            <EditorComponent
@mordv , хороший ли это вариант взаимодействия компонентов с использованием стора?

2024-11-08 09:34 UTC, mordv commented on src/components/card/FlippingCard.tsx
>            <EditorComponent
Чем проще, тем лучше. Нужно хранить activeCardId и делать action setForCard(id,side,data) activeSTRUCTURE я не храню, ее ведь можно выбрать селектором (селектор будет использовать id)
Вообще, надо глубже копнуть. У вас же карточки хранятся на бекенде, смысла их держать в сторе, возможно, нет.

2024-11-08 22:00 UTC, KozlovKV commented on src/components/card/FlippingCard.tsx
>            <EditorComponent
По большей части да. Пока нет полноценной связи с бэком, приходится что-то выдумывать для симуляции работы с ним - потом от много избавлюсь.

Тут скорее был вопрос про прокидывание внутрь компонента для редактирования текста отдельными пропсами состояния текстового поля и функции для его изменения

2024-11-08 22:00 UTC, KozlovKV commented
Добавил компонент для связывания с коллекциями. Всё больше и больше напрашивается разделение FlippingCard на насколько компонентов

2024-11-11 07:54 UTC, KozlovKV commented
@mordv , теперь тут сделано почти всё, что планировал за эту неделю. Разве что ещё хочу добавить кнопку со всплывающим окном для загрузки файлов

2024-11-14 05:43 UTC, KozlovKV commented
- [ ] Перенести кнопку превью вверх
- [ ] Long-plan: загрузка файлов по drag&drop

2024-11-14 05:50 UTC, mordv requested changes

2024-11-14 05:50 UTC, mordv commented on src/components/editor/EditorComponent.tsx
> +  const [uploadedLink, setUploadedLink] = useState<string | undefined>(
| undefined не надо, пустые скобки useState<string>() он поймет и так

2024-11-16 07:23 UTC, KozlovKV commented
> * Перенести кнопку превью вверх
> * Long-plan: загрузка файлов по drag&drop

Делать буду в рамках таска #22

2024-11-16 07:23 UTC, merged