Improve routes logic
FIT-2024-RecALL/recall-front pull request #30
Opened 2024-11-23 08:01 UTC by KozlovKV

2024-11-23 19:57 UTC, KozlovKV commented on src/pages/TrainPage.tsx
> +  const cards = useAppStore(useShallow((state) => state.cardsToTrain));
@mordv , есть ли тут хоть какой-то толк от `useShallow`?

2024-11-25 04:28 UTC, mordv requested changes

2024-11-25 04:28 UTC, mordv commented on src/pages/TrainPage.tsx
> +function getCardExample(id: number): CardType {
Реши для себя какой тип функций используешь - стрелочную или function и старайся использовать только его.

2024-11-25 04:28 UTC, mordv commented on src/pages/TrainPage.tsx
> +  const cards = useAppStore(useShallow((state) => state.cardsToTrain));
1) Слишком много полей в глобальном состоянии. Приложение ведет себя так, будто у него нет бекенда. 
2) toTrain я бы хранил как массив id и писал бы хитрый селектор, который выбирал их из стора. Но вообще, в таком приложении я бы не держал стор вовсе.

2024-11-25 04:28 UTC, mordv commented on src/components/card/TrainCardControls.tsx
> +  const onClikcTrainButton = () => {
typo

2024-11-25 04:28 UTC, mordv commented on src/pages/TrainPage.tsx
> +  const cards = useAppStore(useShallow((state) => state.cardsToTrain));
Если API готов (должен уже быть), можно использовать https://github.com/stoplightio/prism для ускорения разработки

2024-11-25 04:28 UTC, mordv commented on src/state/slices/AuthWindowState.ts
> +          break;
Просто ради интереса попробуй state.authWindow = match(state.authWindow).with('', () => '')......
Switch смотрится убого в функциональном языке. Да и в целом.

2024-11-25 11:30 UTC, KozlovKV commented on src/pages/TrainPage.tsx
> +function getCardExample(id: number): CardType {
Я специально функции-заглушки писал так, чтобы они больше взгляд мазолили XD

2024-11-25 11:35 UTC, KozlovKV commented on src/components/card/TrainCardControls.tsx
> +  const onClikcTrainButton = () => {
Of course. Это тоже заглушка (хотя её я почему-то объявил как стрелочную...)

2024-11-25 13:04 UTC, mordv requested changes

2024-11-25 13:04 UTC, mordv commented on src/state/slices/AuthWindowState.ts
> +        .run();
.exhaustive() - компилятор проверит, что ты перебрал ВСЕ варианты. 
.run() лучше не использовать - он кидает исключение в рантайме
В твоем случае, можно сделать .otherwise(() => 'hidden'). Однако, если ты в будущем вдруг добавишь к authWindow еще одну опцию, exhaustive тебя поймает, otherwise нет.

2024-11-25 20:13 UTC, KozlovKV commented on src/pages/TrainPage.tsx
> +  const cards = useAppStore(useShallow((state) => state.cardsToTrain));
Вынес данные карточек из стора и оставил там храниться только IDшники. Бэк постепенно начинаю прикручивать (скоро будет PR с рабочей авторизацией)

2024-11-27 06:35 UTC, merged