Working authentication
FIT-2024-RecALL/recall-front pull request #32
Opened 2024-11-25 20:25 UTC by KozlovKV

2024-11-25 20:26 UTC, KozlovKV commented
*Папка api автогенерируемая*

2024-11-27 05:01 UTC, KozlovKV commented
Немного ссылок на материалы по react-query (позже оформлю страничку на Випи)
- [Старт](https://tanstack.com/query/latest/docs/framework/react/quick-start)
- [Запросы](https://tanstack.com/query/latest/docs/framework/react/guides/queries)
- [Мутации](https://tanstack.com/query/latest/docs/framework/react/guides/mutations)

2024-11-27 05:06 UTC, KozlovKV commented on src/query/hooks.ts
> +export const getErrorObject = (response: Response, error: any) => {
Вот эта штука мне очень не нравится... Я бы хотел сделать функцию, которая будет принимать в себя
- либо промис запроса и применять к нему базовый then, выделяющий данные либо кидающий ошибку,
- либо функцию запроса и возвращать эту функцию, обёрнутую в функцию высшего порядка, внутри которой такой же then Добавится к вызову промиса

Но возникает проблема в типах, нормальное решение которой я пока не придумал

2024-11-27 05:06 UTC, KozlovKV commented on src/components/mainWrapper/Header.tsx
> +      logoutUserUsersLogoutPost().then(({ data, response, error }) => {
Речь вот об этом then, который везде повторяется

2024-11-29 10:32 UTC, KozlovKV commented
@mordv , вроде сделал чуть более приличную функцию обёртку, которая не ломает тип возвращаемого с бэка объекта. Зацените )

2024-11-30 10:46 UTC, mordv requested changes
См. комментарий про satisfies

2024-11-30 10:46 UTC, mordv commented on src/query/hooks.ts
> +  if (error satisfies HTTPSingleErrorType) return new Error(error.detail);
Хитрый какой :)
В js нет ни satisfies ни HTTPSingleErrorType. Вот результат компиляции для dataExtractionWrapper
было
```ts
    if (error && (error satisfies HTTPSingleErrorType))
      throw new Error(error.detail);
```

стало
```js
    if (error && error)
        throw new Error(error.detail);
```

2024-11-30 10:46 UTC, mordv commented on src/query/hooks.ts
> +  if (error satisfies HTTPSingleErrorType) return new Error(error.detail);
То есть, satisfies это чисто для типов оператор, в runtime ты ничего хитрее `"field" in object` не затянешь. Есть еще конечно instanceof - но не стоит эту тему вскрывать :)

2024-11-30 10:46 UTC, mordv commented on src/components/mainWrapper/Header.tsx
> +      logoutUserUsersLogoutPost().then(({ data, response, error }) => {
Ну закатай его в 
```ts
const f = <Data, Error, More...>({data, error}: {data?: Data, error?: Error}) : Data => {...}
```
Может этого хватит? Я с бека возвращаю тип {status: 'ok', data: T} | {status: 'error', error: E} и через guard проверяю по статусу что мне пришло. Так, при проверке if (status === 'ok') TS знает, что в объекте есть поле data, но нет поля error.

2024-11-30 10:46 UTC, mordv commented on src/components/mainWrapper/Header.tsx
> +      logoutUserUsersLogoutPost().then(({ data, response, error }) => {
Это, вижу, ты уже поправил. Про satisfies комментариц остается актуальным

2024-11-30 19:59 UTC, KozlovKV commented on src/query/hooks.ts
> +  if (error satisfies HTTPSingleErrorType) return new Error(error.detail);
`typeof error?.detail === 'string'` в качестве условия норм будет?

2024-12-02 05:27 UTC, mordv approved these changes

2024-12-02 10:11 UTC, merged